### ISSUE TITLE
Errors in missing value imputation

### ISSUE THREAD

**Issue by bartoszzielinski** [SCI2SUGR/KEEL#5]
I try to process 5-fold CV regression (LinearLMS-R) on the following data set:
https://drive.google.com/open?id=0B8OwcDGp-inrWlNRWllRTHhJX0E

I pre-process data with different Missing Values methods, because there is a lot of missing values.

I obtain the following problems (I use default parameters everywhere):

1. when using SVMimpute-MV before regression, the script generates svmImpute-MV.forestFiresMissing-5-1tra.dat with <null> in it (all the other *.dat files in folder svmImpute-MV.forestFiresMissing also contains <null>).

2. when using KMeans-MV before regression, the script hangs out just after the following output:

*** BEGIN OF EXPERIMENT Mon Nov 21 21:07:18 CET 2016
Executing: java -Xmx512000000  -jar   ../exe/MV-KMeans.jar ./KMeans-MV/50___concrete___mar/config0s0.txt Opening the file: ../datasets/50___concrete___mar/50___concrete___mar-5-1tra.dat.
 >> processing: a0, a1, a2, a3, a4, a5, a6, a7
   > inputs attribute considered: a0.
   > inputs attribute considered: a1.
   > inputs attribute considered: a2.
   > inputs attribute considered: a3.
   > inputs attribute considered: a4.
   > inputs attribute considered: a5.
   > inputs attribute considered: a6.
   > inputs attribute considered: a7.
 >> processing:  a8
   > outputs attribute considered: a8.
 >> Size of the output is: 1
 >> Processing inputs and outputs
 The number of output attributes is: 1

  > Reading the data 
    > Number of instances read: 824

  > Finishing the statistics: (isTrain)true, (# out attributes)1
  >> File LOADED CORRECTLY!!

**Comment by JLuengo** [comment]
Hi.
The issue with SVMImpute seemed to lack some wording in the sentences. I think you may wanted to indicate that the processed training set still contains '<null>' (missing values) after applying SVMImpute. Please clarify this.

I'll check what's going on with KMeans meanwhile (it is a slow process tough). I'd appreciate if you provide us the training and test partitions that are being problematic, so we can speed up the fixing process. 
Is the link to drive the training partition or just the complete data set? 
Please take into account that creating my own partitions from your data may not yield the same problems.

Regards.

**Comment by bartoszzielinski** [comment]
Hi,

Thank for answering!

1.
When using SVMimpute-MV, the intermediate folders with filled dataset are created in folder data. Those datasets are then used in regression.
I check those folders after the whole process.
It generates svmImpute-MV.forestFiresMissing-5-1tra.dat with NULL values in it (all the other *.dat files in folder svmImpute-MV.forestFiresMissing also contains NULL values).
Shouldn't they all be filled before regression?

2.
Here you can find the partitions:
https://drive.google.com/open?id=0B8OwcDGp-inrOUtlbDBnSDNuNUE

Regards!

**Comment by JLuengo** [comment]
Hi.
As you say, the partitions 'should' be filled after imputing. 

However, the problem, as I can see from your data, is that you have so many missing values that very few instances are complete (if any). SVMImpute, in particular, was formulated to create a model using complete instances: it requires instances without missing values to work. If SVMimpute cannot find any of such complete instances, it will leave the missing value as '<null>', since no imputation can be performed. 
Please bear in mind that this is the way it was described in the original research paper from which we implemented it.

However, not all is lost. Other imputation techniques (like KNNimpute) do not have this restrictions and they work looking for observed data in the attributes needed per each instance, and thus should be less problematic in problems with large portions of missing data.

I will take a look on KMeansImpute. It is a slow technique (and FKmeansImpute is even slower), and I will check whether it is stagnating indefinitely or it just needs time.

Regards.

**Comment by bartoszzielinski** [comment]
Have you checked what is going on?

Regards,
Bartosz

**Comment by JLuengo** [comment]
Hi.

Yes, I could check that the problem of SVMimpute with your forest_mcar data set is just that you do not have any complete instance. SVMImpute just won't work on these kind of data sets as was originally described.

To check whether KMeansImpute has any problem or not, I'd appreciate if you could attach me your partitions of 'concrete' data set. Otherwise it'll take me ages to discover what's happening :(

**Comment by bartoszzielinski** [comment]
I have the same problem for forest dataset.
Here you can find the partitions:
https://drive.google.com/open?id=0B8OwcDGp-inrOUtlbDBnSDNuNUE

**Comment by JLuengo** [comment]
As far I can tell, KMeansImpute is working nicely for me in the forest data set.
In https://drive.google.com/open?id=0B9uml4Nwfms7ZElTT0RRQm5VVVU you may check the imputation results for your patitions by using a fresh Github download of KEEL. 

My config file was:

_algorithm = K-means Imputation
inputData = "C:/eclipse/50___forest_fires___mcar/50___forest_fires___mcar-5-5tra.dat" "C:/eclipse/50___forest_fires___mcar/50___forest_fires___mcar-5-5tst.dat" 
outputData = "C:/eclipse/KMeans-MVs0.50___forest_fires___mcar-5-5tra.dat" "C:/eclipse/KMeans-MVs0.50___forest_fires___mcar-5-5tst.dat" 

seed = 1343278692
k = 10
error = 100
iterations = 100_

Of course the paths are not the same as yours, as I ran each partition separately in eclipse to check possible problems (that didn't appear). But the parameters (seed, etc.) should be similar to yours.

**Comment by bartoszzielinski** [comment]
Could you check this set:
https://drive.google.com/open?id=0B8OwcDGp-inrN0d5ZGNQRXVINWM
I have same problem with this one...

Bartosz

**Comment by JLuengo** [comment]
Hi.
As you said, KmeansImpute were hanging with these data sets. Again, you have an extreme case where only 2 instances are complete in your "friedman" data set and you want 10 clusters (and thus 10 initial centroids created from 10 complete instances that do not exist).

I have reworked the code to accept incomplete instances (hoping that the cluster updating process will complete the missing features in the centroids). It is already in the master branch, so you can download it and give it a try.
Regards.

**Comment by bartoszzielinski** [comment]
I see - this sounds resonable.
Data are very extreme - this is what we are currently working on. :)

Thanks a lot for help.

Do I have to compile sources to get the newest version, or maybe I can download somewhere the actual jar?

**Comment by JLuengo** [comment]
Once you pull the source from the code, you should compile again with ant to get the jar.

**Comment by bartoszzielinski** [comment]
Jupi!
It's working! :)
Thanks!

**Comment by bartoszzielinski** [comment]
Unfortunatelly, I have a nother problem with KMeans.

Here you can find both, the input partitions, as well as the result of applying KMeans-MV imputation):
https://drive.google.com/open?id=0B8OwcDGp-inrWjVESms5NjY4NDA

As you can see, KMeans-MVs0.mortgage___75___mar-5-1tst.dat contains <null> elements (only one, what is quite strange, but still).

Is it because of the limitation of the method or it is a  bug?

Kind regars,
Bartosz

**Comment by bartoszzielinski** [comment]
Have you found out what is going wrong?

Bartosz

**Comment by JLuengo** [comment]
Again, you have a data set with a massive amount of MVs. You'll find that you lack of information to create imputations for your MVs, and in the case of KMeansImputation, the higher the number of centroids (parameter k) you select, the higher the probability of obtaining "<null>" instead of a value in your imputations.

I do not know the point of having such data sets with 75% of MCAR MVs, but there is a limit about what imputation algorithms can do. And journal papers about imputation in Data Mining rarely reach 50%.

If you really want to impute these data sets, lower the number of clusters so you'll have more chances of obtaining complete centroids (with all their features/dimensions observed). But this is not a coding problem: you are just puting ML-based imputations at their limit.

Regards.
